config/routes.rb
Rails.application.routes.draw do

  root to: 'lists#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users

  resources :lists do
    resources :items
  end

  resources :sessions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  private

  def logged_in?
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :logged_in?
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @list = List.find(params[:list_id]).order("published_at DESC")
    @item = Item.all
  end

  def new
    @list = List.find(params[:list_id])
    @item = Item.new
  end

  def create
    @list = List.find(params[:list_id])
    @item = @list.items.new(item_params)

    if @item.save
      redirect_to @list
      flash[:notice] = "Item saved successfully."
    else
      redirect_to @list
      flash[:error] = "Item could not be saved."
    end
  end

  def show

    @item = Item.find(params[:id])

    # @comment = @post.comments.new
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :rank, :note, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @items = Item.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(allowed_params)
      redirect_to @list, notice: 'List has been updated'
    else
      render :edit
    end
  end

  private

  def allowed_params
    params.require(:list).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!', class: 'alert alert-success', role: 'alert'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(allowed_params)
    if @user.save
      redirect_to root_url, notice: 'Thank you for signing up!'
      session[:user_id] = @user.id
    else
      render :new
    end
  end

  private
  def allowed_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h2 class="tbspace">New Item</h2>

      <%= form_for([@list, @item]) do |f| %>
      <% if @item.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% else %>

      <div class="form-group">
        <!-- <label class="sr-only" for="exampleInputAmount">Email Address</label> -->
        <div class="input-group">
          <div class="input-group-addon">@</div>
          <%= text_field_tag :name, params[:name], id: 'input-name', class: 'form-control form-control-lg', placeholder: 'Name' %>
          <!-- <input type="text" class="form-control" id="exampleInputAmount" placeholder="Email"> -->
        </div>
      </div>


      <div class="form-group">
        <!-- <label class="sr-only" for="exampleInputAmount">Email Address</label> -->
        <div class="input-group">
          <div class="input-group-addon">🗒</div>
          <%= text_area_tag :note, params[:note], id: 'input-note', rows: '4', class: 'form-control form-control-lg', placeholder: 'Note' %>
          <!-- <input type="text" class="form-control" id="exampleInputAmount" placeholder="Email"> -->
        </div>
      </div>

      <%= f.hidden_field :list_id, :value => params[:id]  %>

      <div class="actions"><%= submit_tag "Create", class: 'btn btn-info' %></div>
      <!-- <button type="submit" class="btn btn-primary">Log In</button> -->

      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZipPilot</title>
  <%= csrf_meta_tags %>

  <!-- Add jQuery  -->
  <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>

  <!-- Add Tether -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/css/tether.min.css" integrity="sha256-y4TDcAD4/j5o4keZvggf698Cr9Oc7JZ+gGMax23qmVA=" crossorigin="anonymous" />

  <!-- Add Bootstrap 4 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <nav class="navbar navbar-light bg-faded">
    <a class="navbar-brand" href="#">ZipPilot</a>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>

    </ul>
    <div class="float-xs-right">
    <% if logged_in? %>
    <%= link_to 'Logout', logout_path, class: "btn btn-outline-warning"%>
    <% else %>
    <%= link_to "Sign Up", signup_path, class: "btn btn-outline-info" %>
    <%= link_to "Log In", login_path, class: "btn btn-outline-primary" %>
    <% end %>
    </div>
  </nav>

  <div id="user_header">

  </div>
  <div id="container">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/lists/_list.html.erb
  <%= link_to list.name, list, class: "list-group-item list-group-item-action" %>

app/views/lists/edit.html.erb
<div class="col-md-6 offset-md-3 px-0">
  <h2 class="tbspace">Edit List</h2>

  <%= form_for @list do |f| %>
  <% if @list.errors.any? %>
  <div class="error_messages">
    <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
    <ul>
      <% @list.errors.full_messages.each do |msg| %>
      <li>
        <div class="alert alert-success" role="alert">
           <%= msg %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
  <% else %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'form-control'%>
  </div></br>
  <div class="actions"><%= f.submit(class:"btn btn-primary") %></div>
  <% end %>
  <% end %>
</div>

app/views/lists/index.html.erb
<% if logged_in? %>
<div class="container"><div class="col-sm-3 offset-sm-9">
  <%= link_to "New List", new_list_path, class:"btn btn-outline-info" %>
</div>
<div class="col-lg-6 offset-lg-3">
  <h2>My Lists</h2>
  <div id="lists">
    <%= render @lists %>
  </div>
</div>
</div>
<% else %>
<div class="row">
  <div class="col-xs-4 offset-xs-4" id="signin">
    <%= link_to "Sign Up", signup_path, class:"btn btn-outline-primary btn-primary btn-block my-1" %>
  </div>
</div>
<div class="row">
  <div class="col-xs-4 offset-xs-4" id="signin">
    <%= link_to "Sign In", login_path, class:"btn btn-outline-info btn-info btn-block my-1" %>
  </div>
</div>
<% end %>

app/views/lists/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 offset-lg-4">
      <h2 class="tbspace">Sign Up</h2>

      <%= form_for @list do |f| %>
      <% if @list.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% @list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% else %>

      <div class="form-group">
        <!-- <label class="sr-only" for="exampleInputAmount">Email Address</label> -->
        <div class="input-group">
          <div class="input-group-addon">@</div>
          <%= text_field_tag :name, params[:name], id: 'input-name', class: 'form-control form-control-lg', placeholder: 'Name' %>
          <!-- <input type="text" class="form-control" id="exampleInputAmount" placeholder="Email"> -->
        </div>
      </div>

      <div class="actions"><%= submit_tag "Create", class: 'btn btn-info' %></div>
      <!-- <button type="submit" class="btn btn-primary">Log In</button> -->

      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="col-lg-12">
    <div class="row">
      <% if flash[:notice] %>
      <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
      <% end %>
      <div class="col-sm-8">
        <h2 class="tbspace"><%= @list.name %> <%= link_to "✎", edit_list_path(@list), class: "btn btn-outline-info btn-sm" %></h2>
      </div>
      <div class="col-sm-4 offset-sm-8">

        <ul class="list-group">
          <%= @list.items.each do |r| %>
          <li class="list-group-item">
            <span class="tag tag-default tag-pill float-xs-right">14</span>
            <%= r.name %>
          </li>
          <% end %>
        </ul>

      </div>
      <div class="col-lg-12">
        <%= link_to "New Item", new_list_item_path(@list), class: "btn btn-outline-success btn-sm" %>

        <%= link_to "Browse Lists", lists_path, class: "btn btn-outline-primary btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 offset-lg-4">
      <h2 class="tbspace">Sign Up</h2>

      <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% else %>

      <div class="form-group">
        <!-- <label class="sr-only" for="exampleInputAmount">Email Address</label> -->
        <div class="input-group">
          <div class="input-group-addon">✉️</div>
          <%= text_field_tag :email, params[:email], id: 'input-email', class: 'form-control form-control-lg', placeholder: 'Email' %>
          <!-- <input type="text" class="form-control" id="exampleInputAmount" placeholder="Email"> -->
        </div>
      </div>
      <div class="form-group">
        <!-- <label class="sr-only" for="exampleInputAmount">Email Address</label> -->
        <div class="input-group">
          <div class="input-group-addon">🔒</div>
          <%= password_field_tag :password, params[:password], id: 'input-password', class: 'form-control form-control-lg', placeholder: 'Password' %>
          <!-- <input type="text" class="form-control" id="exampleInputAmount" placeholder="Email"> -->
        </div>
      </div>
      <div class="form-group">
        <!-- <label class="sr-only" for="exampleInputAmount">Email Address</label> -->
        <div class="input-group">
          <div class="input-group-addon">🔒</div>
          <%= password_field_tag :password_confirmation, params[:password_confirmation], id: 'input-password-confirmation', class: 'form-control form-control-lg', placeholder: 'Password Confirmation' %>
          <!-- <input type="text" class="form-control" id="exampleInputAmount" placeholder="Email"> -->
        </div>
      </div>
      <div class="actions"><%= submit_tag "Sign Up", class: 'btn btn-info' %></div>
      <!-- <button type="submit" class="btn btn-primary">Log In</button> -->

      <% end %>
      <% end %>
    </div>
  </div>
</div>